default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["pg_user"] %>
  password: <%= ENV["pg_password"] %>

development:
  <<: *default
  database: budgeter_development

test:
  <<: *default
  database: budgeter_test

production:
  <<: *default
  database: budgeter_production
